In [6]:
import pandas as pd
import os
import sys

sys.path.append("../")

In [7]:
from config import *

zip_data_loc = os.path.join(INTERIM_DATA_DIR, "zip_level_metrics.csv")
zip_df = pd.read_csv(zip_data_loc)

In [8]:
PRIMARY_KEY_COLS = ['Zip Code']
raw_metric_cols = [
    col for col in zip_df.columns \
    if col not in PRIMARY_KEY_COLS \
        and 'Rank' not in col
]

In [9]:
# TODO: create Metric class that has all of these mappings baked into the class.
HEALTH_METRICS = [
    'Food Access',
    'Binge drinking',
    'Diabetes',
    'Frequent mental distress',
    'Frequent physical distress',
    'Obesity',
    'Physical inactivity',
    'Preventive services',
    'Smoking',
    'Medicaid Claims Per Capita',
    'Medicaid Recipients Per Capita',
    'Medicaid Dollar Amt. Per Capita',
    'ER Claims Per Capita',
    'ER Recipients Per Capita',
    'ER Dollar Amt. Per Capita',
    'Mental Health Claims Per Capita',
    'Mental Health ER Claims Per Capita',
    'Mental Health Patients Per Capita',
    'Mental Health Dollar Amt. Per Capita',
    'Life expectancy',
    'Limited access to healthy foods',
    'Uninsured'
]

CRIME_METRICS = [
    'All Arrests Per Capita',
    'Drug Arrests Per Capita',
    'Violent Arrests Per Capita',
    'Theft/Trespassing Arrests Per Capita',
    'Weapon Arrests Per Capita',
    'UCR Index Crime Per Capita',
    'UCR Homicide Per Capita',
    'UCR Rape Per Capita',
    'UCR Agg. Assault Per Capita',
    'UCR Robbery Per Capita',
    'UCR Burglary Per Capita'
]

HOUSING_ENVIRONMENT_METRICS = [
    'Eviction Rate',
    '% Renter Occupied',
    'Lead exposure risk index',
    'Park access',
    'Median Household Income',
    'Income Inequality',
    'Poverty Rate',
    'Racial/ethnic diversity',
    'Unemployment',
    'Children in Poverty',
]

EDUCATION_METRICS = [
    'Access to Quality PreK',
    'Quality Schools',
    'High School Graduation Rate'
]

health_df = zip_df[[*PRIMARY_KEY_COLS, *HEALTH_METRICS]]
crime_df = zip_df[[*PRIMARY_KEY_COLS, *CRIME_METRICS]]
housing_env_df = zip_df[[*PRIMARY_KEY_COLS, *HOUSING_ENVIRONMENT_METRICS]]
educ_df = zip_df[[*PRIMARY_KEY_COLS, *EDUCATION_METRICS]]

In [10]:
educ_df.describe()

,Zip Code,Access to Quality PreK,Quality Schools,High School Graduation Rate
count,40.000000,37.000000,36.000000,22.000000
mean,46218.325000,69.118919,51.147222,78.631818
std,40.029084,22.456969,31.846413,21.938190
min,46077.000000,16.800000,0.000000,3.000000
25%,46207.500000,63.100000,27.250000,79.350000
50%,46224.500000,72.500000,45.150000,85.600000
75%,46237.500000,85.800000,81.350000,90.750000
max,46278.000000,100.000000,100.000000,97.600000

In [11]:
housing_env_df.describe()

,Zip Code,Eviction Rate,% Renter Occupied,Lead exposure risk index,Park access,Median Household Income,Income Inequality,Poverty Rate,Racial/ethnic diversity,Unemployment,Children in Poverty
count,40.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000
mean,46218.325000,6.454865,43.147568,5.368133,34.994758,49911.793784,-10.943011,16.067297,55.005876,7.130406,24.825306
std,40.029084,3.538816,19.568329,2.659455,27.490148,21117.385430,21.884775,10.648621,12.747109,3.629275,15.342697
min,46077.000000,0.000000,5.490000,1.000000,2.000000,21798.910000,-48.363636,2.000000,25.500000,2.500000,0.000000
25%,46207.500000,3.420000,28.720000,3.000000,11.428571,34086.330000,-26.600000,6.480000,47.600000,4.000000,12.090909
50%,46224.500000,6.270000,48.270000,5.727273,24.833333,45255.290000,-11.800000,15.340000,53.166667,6.500000,25.000000
75%,46237.500000,8.510000,54.940000,7.375000,54.363636,59711.670000,0.333333,22.360000,65.428571,8.818182,40.666667
max,46278.000000,13.530000,80.290000,9.928571,87.833333,121379.000000,47.000000,38.010000,80.000000,17.375000,49.500000

In [12]:
housing_env_df.describe()

,Zip Code,Eviction Rate,% Renter Occupied,Lead exposure risk index,Park access,Median Household Income,Income Inequality,Poverty Rate,Racial/ethnic diversity,Unemployment,Children in Poverty
count,40.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000
mean,46218.325000,6.454865,43.147568,5.368133,34.994758,49911.793784,-10.943011,16.067297,55.005876,7.130406,24.825306
std,40.029084,3.538816,19.568329,2.659455,27.490148,21117.385430,21.884775,10.648621,12.747109,3.629275,15.342697
min,46077.000000,0.000000,5.490000,1.000000,2.000000,21798.910000,-48.363636,2.000000,25.500000,2.500000,0.000000
25%,46207.500000,3.420000,28.720000,3.000000,11.428571,34086.330000,-26.600000,6.480000,47.600000,4.000000,12.090909
50%,46224.500000,6.270000,48.270000,5.727273,24.833333,45255.290000,-11.800000,15.340000,53.166667,6.500000,25.000000
75%,46237.500000,8.510000,54.940000,7.375000,54.363636,59711.670000,0.333333,22.360000,65.428571,8.818182,40.666667
max,46278.000000,13.530000,80.290000,9.928571,87.833333,121379.000000,47.000000,38.010000,80.000000,17.375000,49.500000

In [13]:
health_df.describe()

,Zip Code,Food Access,Binge drinking,Diabetes,Frequent mental distress,Frequent physical distress,Obesity,Physical inactivity,Preventive services,Smoking,...,ER Claims Per Capita,ER Recipients Per Capita,ER Dollar Amt. Per Capita,Mental Health Claims Per Capita,Mental Health ER Claims Per Capita,Mental Health Patients Per Capita,Mental Health Dollar Amt. Per Capita,Life expectancy,Limited access to healthy foods,Uninsured
count,40.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,...,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,3.700000e+01,37.000000,37.000000,37.000000
mean,46218.325000,71.121622,17.708557,11.555677,14.891785,13.443623,35.280326,29.038335,30.152811,21.711506,...,279.764054,88.685135,41803.596216,1720.632973,75.070811,25.474865,2.587976e+05,76.201248,72.454149,12.158284
std,40.029084,24.620059,2.288846,3.185715,2.996413,3.254410,5.452788,6.322318,5.082302,5.434149,...,197.824319,53.130605,32996.586050,1341.058501,81.105681,17.874904,1.987431e+05,3.370771,19.159085,5.474798
min,46077.000000,9.100000,11.545455,7.250000,10.000000,9.000000,27.000000,18.000000,19.636364,12.000000,...,25.210000,9.420000,4457.330000,167.380000,0.000000,2.930000,2.380603e+04,68.400000,0.000000,1.000000
25%,46207.500000,59.400000,16.428571,9.000000,13.000000,11.000000,31.000000,24.000000,26.333333,18.000000,...,139.210000,49.940000,18104.460000,889.450000,29.790000,12.990000,1.314208e+05,74.000000,61.900000,8.500000
50%,46224.500000,77.800000,17.666667,11.333333,14.500000,12.571429,34.285714,27.857143,30.000000,20.900000,...,238.300000,82.590000,31237.200000,1372.460000,50.410000,20.670000,2.082547e+05,77.000000,75.000000,12.000000
75%,46237.500000,89.700000,19.000000,12.750000,17.375000,16.333333,38.500000,34.500000,35.000000,26.625000,...,413.900000,122.800000,59362.220000,2231.200000,100.390000,34.760000,3.334168e+05,79.000000,85.500000,16.000000
max,46278.000000,100.000000,22.000000,22.272727,20.500000,20.636364,49.181818,42.727273,39.000000,32.000000,...,936.390000,213.660000,172272.980000,7892.290000,464.980000,99.710000,1.178280e+06,81.666667,100.000000,23.000000

In [14]:
len(HOUSING_ENVIRONMENT_METRICS)

10

In [16]:
print(educ_df.shape)
print(len(educ_df['Zip Code'].unique().tolist()))

(40, 4)
40